### PR TITLE
Refactored Main to show relationships between parts clearly.

### PR DESCRIPTION
**Pull request by benhardy**

### CODE REVIEW

**Comment by janbartel** [comment]
Hi Ben,

Thanks for the patch. It looks like your ide has reformatted a lot of the code, making it difficult to concentrate attention on the parts that have actually changed. Plus, we would like to keep the code in the general jetty coding standards (http://www.eclipse.org/jetty/documentation/current/coding-standards.html). Could you redo the patch and apply the correct formatting? Thanks.

**Comment by benhardy** [comment]
sure, will do. sorry about that!

**Comment by benhardy** [comment]
Hi @janbartel - I've updated the PR with the project formatting, rearranged the method order to more closely follow the existing execution order for easy diffing, and separated the proposed changes into 2 commits. I have some other ideas but will save them for future patches. Cheers!

**Comment by janbartel** [comment]
Hi Ben, I applied your changes, thanks for reformatting them. I've also just done some commits that supports the latest jetty-9.2.6, based on your changes. Thanks. Jan.

**Pull request merged**
